version: "3.7"

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatsby-landing-dev
    ports:
      - 8000:8000
    volumes:
      - ./:/app/gatsby-landing
